FROM python:3.7
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . .
WORKDIR /app/src
RUN if [ ! -d uploads ] ; then mkdir ./uploads ; fi
CMD [ "flask", "--app", "api.py", "run", "--host", "0.0.0.0", "--port", "5001" ]
