services:
  backend:
    build:
      dockerfile: ./Dockerfile-backend
    environment:
      BACKEND_PORT: $BACKEND_PORT
    volumes:
      - .:/app
      - /app/.venv/
    ports:
      - "$BACKEND_PORT:$BACKEND_PORT"
  frontend:
    build:
      dockerfile: ./Dockerfile-frontend
    environment:
      VITE_BACKEND_PORT: $BACKEND_PORT
      VITE_FRONTEND_PORT: $FRONTEND_PORT
    volumes:
      - ./frontend/concretize-frontend:/app
      - /app/node_modules/
    ports:
      - "$FRONTEND_PORT:$FRONTEND_PORT"
