FROM python:3.7
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
WORKDIR /app/src
RUN if [ ! -d uploads ] ; then mkdir ./uploads ; fi
CMD flask --app api.py --debug run --host 0.0.0.0 --port $BACKEND_PORT
