version: '3'
services:
  backend:
    build:
      dockerfile: ./Dockerfile-backend
    ports:
      - "5001:5001"
  frontend:
    build:
      dockerfile: ./Dockerfile-frontend
    ports:
      - "5173:5173"
