services:
  backend:
    build:
      dockerfile: ./Dockerfile-backend
      args:
        BACKEND_PORT: $BACKEND_PORT
    volumes:
      - ./output:/app/output
    ports:
      - "$BACKEND_PORT:$BACKEND_PORT"
  frontend:
    build:
      dockerfile: ./Dockerfile-frontend
      args:
        BACKEND_PORT: $BACKEND_PORT
        FRONTEND_PORT: $FRONTEND_PORT
    ports:
      - "$FRONTEND_PORT:$FRONTEND_PORT"
