services:
  backend:
    build:
      dockerfile: ./Dockerfile-backend
    volumes:
      - ./output:/app/output
    ports:
      - "5001:5001"
  frontend:
    build:
      dockerfile: ./Dockerfile-frontend
    ports:
      - "5173:5173"
